name: build

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc

      - name: Install Build Dependencies
        run: |
          choco install -y cmake nasm
          # Install Microsoft C++ Build Tools via Visual Studio Installer
          curl -sL https://aka.ms/vs/17/release/vs_BuildTools.exe --output vs_BuildTools.exe
          Start-Process -Wait -FilePath ./vs_BuildTools.exe -ArgumentList "--quiet --wait --norestart --nocache --installPath `"$env:ProgramFiles(x86)\Microsoft Visual Studio\2022\BuildTools`" --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended"
        shell: pwsh

      - name: Build for Windows
        run: cargo build --target x86_64-pc-windows-msvc --release --locked

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: target/x86_64-pc-windows-msvc/release/proxygh.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake nasm build-essential

      - name: Build
        run: cargo build --release --locked

      - name: Upload Linux Native Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-native-binary
          path: target/release/proxygh

  build-linux-musl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-musl

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake nasm build-essential musl-tools

      - name: Build
        run: cargo build --target x86_64-unknown-linux-musl --release --locked

      - name: Upload Linux Musl Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-musl-binary
          path: target/x86_64-unknown-linux-musl/release/proxygh

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: proxygh/proxygh
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          outputs: type=docker,dest=/tmp/proxygh-docker-image.tar
          tags: proxygh/proxygh:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Compress Docker image
        run: |
          gzip /tmp/proxygh-docker-image.tar

      - name: Upload Docker image archive
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-archive
          path: /tmp/proxygh-docker-image.tar.gz

  release:
    needs: [build-windows, build-linux, build-linux-musl, build-docker]
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            ./artifacts/linux-native-binary/proxygh
            ./artifacts/linux-musl-binary/proxygh
            ./artifacts/windows-binary/proxygh.exe
            ./artifacts/docker-image-archive/proxygh-docker-image.tar.gz
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
